### ISSUE TITLE
Member Only Task in FTP

### ISSUE THREAD

**Issue by XXVI-III-CX** [source-chunk/chunk-picker-v2#2]
Cooking a baked potato is not possible in FTP but does show up as a chunk task with the option selected.

**Comment by source-chunk** [comment]
Issue is fixed now. Please use the Bug Reporting form found in the top-bar of the website for any future issues. Thanks!

(That link for reference is https://docs.google.com/forms/d/e/1FAIpQLSdmSyeMPMjuDxPrDKQHbCjJe0bXQOUwPYvyTeY_mrF-UrtmCQ/viewform?usp=sf_link )

**Comment by XXVI-III-CX** [comment]
Thanks for the link, can't find it on mobile.
