### ISSUE TITLE
Mobile reloads when entering map ID

### ISSUE THREAD

**Issue by jsparidaans** [source-chunk/chunk-picker-v2#4]
## Summary
On Android Chrome, on either phone or tablet, the site reloads after entering the map ID

## Steps to reproduce 
1. Open Chunk map on Android Chrome
2. Enter or generate a map ID 
3. See the site reload and not showing a chunk map.

**Comment by source-chunk** [comment]
I'm not able to replicate this currently. It could be an issue with the specific map you're trying to load itself. What map were you trying to load when you ran into this problem?

**Comment by jsparidaans** [comment]
It happens with any map I newly generate, it brings me back to the root route and gives the options to generate or enter an ID. When I enter the previously generated ID, it loads and then redirects back to the root.

**Comment by source-chunk** [comment]
There was likely an issue that happened during map creation then, which I will look in to. I'm guessing some of the maps you're trying to create are failing to create for various reasons, although I would need to know what the mapcodes were to actually look at them myself.

Also in the future, please use the Bug Report Google form that you can find on the website itself, or found here: https://docs.google.com/forms/d/e/1FAIpQLSdmSyeMPMjuDxPrDKQHbCjJe0bXQOUwPYvyTeY_mrF-UrtmCQ/viewform

**Comment by jsparidaans** [comment]
Sorry, I meant to include an example map ID but then completely forgot. It happens for example with `OEWC`
